name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        working-directory: docs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs==1.6.1
          pip install mkdocs-material==9.6.14
          pip install mkdocstrings==0.29.1
          pip install mkdocstrings-python==1.16.10
          pip install mkdocs-autorefs==1.4.2
          pip install mkdocs-jupyter==0.25.1
         
      - name: Build docs
        working-directory: docs
        run: mkdocs build
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./docs/site
          force_orphan: true